server:
  port: 8761

# Standalone Mode: http://cloud.spring.io/spring-cloud-static/spring-cloud.html#_standalone_mode
# When we'll have peers, this configuration 'll be needed instead: http://cloud.spring.io/spring-cloud-static/spring-cloud.html#_peer_awareness
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#  server:
#    enableSelfPreservation: false
