server:
  port: 8080
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: auth       
        uri: lb://auth
        predicates:
        - Path=/api/core/**
      - id: profile       
        uri: lb://profile
        predicates:
        - Path=/api/profiles/**
