# Search Service Development environment

spring:
  data:
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: localhost:9300

  elasticsearch:
    rest:
      uris: http://localhost:9200

initial-import:
  enabled: true
