# Profile Service Development environment

spring:

  jpa.hibernate.ddl-auto: update
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc.lob.non_contextual_creation: true
  datasource:
    url: jdbc:postgresql://localhost:5432/profile
    username: admin
    password: admin
